name: Save Pricing Data

on:
  schedule:
    - cron: "0 0 * * *"  # Set the schedule for running the action (e.g., daily at midnight)

jobs:
  save_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: pip install requests

      - name: Save Pricing Data
        env:
          API_KEY: ${{ secrets.TSM_API_KEY }}
        run: |
          import requests
          import json
          from datetime import datetime

          api_key = os.environ['API_KEY']
          # Endpoint URLs
auth_url = 'https://auth.tradeskillmaster.com/oauth2/token'
pricing_url = 'https://pricing-api.tradeskillmaster.com/ah/512'
realm_url = 'https://realm-api.tradeskillmaster.com/regions'


# Request body for access token
payload = {
    "client_id": "c260f00d-1071-409a-992f-dda2e5498536",
    "grant_type": "api_token",
    "scope": "app:realm-api app:pricing-api",
    "token": api_key
}

# Get access token
response = requests.post(auth_url, json=payload)
if response.status_code == 201:
    auth_data = response.json()
    access_token = auth_data.get('access_token')
    print("Access token obtained successfully")

    # Make GET request for pricing data
    headers = {'Authorization': f'Bearer {access_token}'}
    pricing_response = requests.get(pricing_url, headers=headers)
    if pricing_response.status_code == 200:
        pricing_data = pricing_response.json()
        print("Pricing data obtained successfully")

        # Save pricing data to items.json
        with open(filename, 'w') as file:
            json.dump({"pricing_data": pricing_data}, file, indent=4)
    else:
        print("Failed to fetch pricing data")
else:
    print("Failed to obtain access token")

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Add latest pricing data JSON file"
          git push
