name: Sorter

on:
  #schedule:
    #- cron: "*/30 * * * *"  # 15 mins
  workflow_dispatch:

jobs:
  save_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: pip install requests

      - name: Save Pricing Data
        run: python sortr.py
        
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Updated day week and month pricing data"
          git push
